# Generated by Django 3.0.7 on 2020-06-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insertmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URNO', models.IntegerField()),
                ('UNAME', models.CharField(max_length=30)),
                ('UPHY', models.IntegerField()),
                ('UCHE', models.IntegerField()),
                ('UMATHS', models.IntegerField()),
            ],
        ),
    ]
