# Generated by Django 3.0.7 on 2020-06-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_qaa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qaa',
            old_name='questions',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='qaa',
            name='lang',
            field=models.CharField(choices=[('j', 'java'), ('p', 'python'), ('c', 'C prog')], max_length=1),
        ),
    ]
